---
title: "DER Potentials"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo=FALSE,
  fig.keep='all',
  cache=TRUE
  )
```


```{r,  cache=FALSE, include=FALSE}
source("MarketFigures.R")
```

```{r}
# MRO	<S3: sfc_GEOMETRY>			
# NPCC	<S3: sfc_GEOMETRY>			
# RFC	<S3: sfc_GEOMETRY>			
# SERC	<S3: sfc_GEOMETRY>			
# SPP	<S3: sfc_GEOMETRY>			
# TRE	<S3: sfc_GEOMETRY>			
# WECC	<S3: sfc_GEOMETRY>	

nerc_region_state_map <- read_csv("nerc_state_mapping.csv")
```



```{r}
market_sum <- left_join(clean_data_ami_all_sup_shp, nerc_region_state_map, by="state_abbr") %>% st_drop_geometry() %>% 
  mutate(
    rooftop_value = replica_mwh * (1000) * dlrs_kwh.x
  ) %>% 
  group_by(
    # eia_id
    # state_abbr,
    NERC#,
    # simplified_utility_type,
    # company_ty,
    # company_na,
    # state_abbr
    # income_bracket
    # energy_burden_poverty,
    # housing_tenure,
    # number_of_units
  ) %>% 
  summarise(
    # efficiency_potential_savings
    # transportation_spend
    # excess_cost_burden,
    #total_rooftop_mwh = sum(replica_mwh, na.rm = TRUE),
    #dlrs_kwh = mean(dlrs_kwh.x, na.rm = TRUE),
    net_energy_return = mean(ner, na.rm=TRUE), 
    rooftop_potential_savings = sum(rooftop_value, na.rm = TRUE),
    electricity_spend = sum(electricity_spend * households, na.rm = TRUE),
    energy_spend = sum(energy_cost * households, na.rm = TRUE),
    .groups="keep"
  ) %>% 
  mutate(
    electrified_spending = electricity_spend / energy_spend,
    electricity_prosumer_ratio = rooftop_potential_savings / electricity_spend,
    energy_prosumer_ratio = rooftop_potential_savings / energy_spend
  ) %>% 
  arrange(
    desc(electricity_prosumer_ratio)
  )
```

```{r}
market_sum %>% filter(energy_spend > 100) %>% write.csv("market_sums.csv")
```


```{r}
market_sum  %>% 
  ggplot(aes(x=electricity_prosumer_ratio, y=net_energy_return, color=NERC, size=energy_spend)) + 
  geom_point() + 
  geom_text(aes(label = NERC), hjust = -0.1, vjust = -0.5) + 
  xlab("Prosumer Ratio (Residential Rooftop Solar Technical Potential Retail Value / Household Power Costs)") + 
  ylab("Net Energy Return") #+ 
 # stat_summary(fun.data= mean_cl_normal) + 
#  geom_smooth(method='lm')
```

```{r}
linear_model = lm(data=market_sum, net_energy_return ~ electricity_prosumer_ratio)
linear_model
# ?mean_cl_normal
```


```{r}
market_sum  %>% 
  ggplot(aes(x=net_energy_return, y=electricity_prosumer_ratio)) + geom_point() + 
  geom_text(aes(label = state_abbr), hjust = -0.1, vjust = -0.5)
```


```{r}
require(gridExtra)

market_sum %>% pivot_longer(cols=c(electricity_prosumer_ratio, energy_prosumer_ratio)) %>%
ggplot(aes(y=net_energy_return, x=value, label = state_abbr, color=name)) + 
  geom_point() + 
  geom_text(hjust = -0.1, vjust = -0.5)+
  geom_segment(data=market_sum,aes(y=net_energy_return, x=electricity_prosumer_ratio, yend=net_energy_return, xend=energy_prosumer_ratio),arrow=arrow(), inherit.aes = FALSE) +
  xlab("Prosumer Ratio ") + 
  ylab("Net Energy Return") +
  theme(legend.position="top", legend.title=element_blank())
  # stat_summary(fun.data= mean_cl_normal) + 
  # geom_smooth(method='lm', show.legend = FALSE)
  # scale_x_reverse() + scale_y_reverse()

# ggplot(data,aes(x = MB_F2_ONGLIDE,y = MB_F1_ONGLIDE,color = SPEAKER,label = VOWEL)) +
#   geom_text(aes(x = MB_F2_ONGLIDE,y = MB_F1_ONGLIDE)) + 
#   geom_text(aes(x = MB_F2_OFFGLIDE,y = MB_F1_OFFGLIDE)) +
#   geom_segment(aes(x = MB_F2_ONGLIDE,y = MB_F1_ONGLIDE,xend = MB_F2_OFFGLIDE,yend = MB_F1_OFFGLIDE,color=SPEAKER),arrow=arrow()) +
#   scale_x_reverse() +
#   scale_y_reverse()
```



```{r}
clean_data_ami_all_sup_shp %>% names()
```

