---
title: "Market Figures"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("MarketFigures.R")
```

```{r}
# C:\Users\Eric Scheier\Documents\apps\net_energy_equity\f8612018\Utility_Data_2018.xlsx
nerc_regions_states <- read_excel("data/f8612018/Utility_Data_2018.xlsx", sheet = "States", skip = 1)
nerc_regions_territories <- read_excel("data/f8612018/Utility_Data_2018.xlsx", sheet = "Territories", skip = 1)
# merge states and territories tabs
nerc_regions <- bind_rows(nerc_regions_states, nerc_regions_territories)
# join with clean data on state_abbr and eia utility number
nerc_regions$`Utility Number` <- as.character(nerc_regions$`Utility Number`)

clean_data_ami_all_sup_shp <- clean_data_ami_all_sup_shp %>% 
  left_join(nerc_regions, by=c("state_abbr"="State","eia_id"="Utility Number"))




# clean_data_ami_all_sup_shp_serc <- clean_data_ami_all_sup_shp %>% 
#   filter(state_abbr %in% 
#            c("AL", #Alabama, 
#              "GA", #Georgia, 
#              "MS", #Mississippi, 
#              "MO", #Missouri, 
#              "NC", #North Carolina, 
#              "SC", #South Carolina, 
#              "TN", #Tennessee, 
#              #and portions of 
#              "AR", #Arkansas, 
#              "IL", #Illinois, 
#              "KY", #Kentucky, 
#              "LA", #Louisiana, 
#              "OK", #Oklahoma, 
#              "TX", #Texas, 
#              "VA", #Virginia, 
#              "FL" #Florida, 
#            )
#   )
```

```{r}
plot(
  (clean_data_ami_all_sup_shp  %>% 
  filter(!(state_abbr %in% c("HI","AK", NA))))["NERC Region"], 
  lwd=0.01
  )
```



```{r}
energy_cost_wm <- calculate_weighted_metrics(st_drop_geometry(clean_data_ami_all_sup_shp), 
                                         group_columns=c("NERC Region"), 
                                         metric_name="energy_cost", 
                                         metric_cutoff_level=0, 
                                         upper_quantile_view=1.0, 
                                         lower_quantile_view=0.0)
energy_cost_wm
```
```{r}
calculate_weighted_metrics(st_drop_geometry(clean_data_fpl_all_sup_shp), 
                                          group_columns=c("simplified_primary_heating_fuel"), 
                                          metric_name="energy_cost", 
                                          metric_cutoff_level=0, 
                                          upper_quantile_view=1.0, 
                                          lower_quantile_view=0.0)
```
```{r}
calculate_weighted_metrics(st_drop_geometry(clean_data_fpl_all_sup_shp), 
                                          group_columns=c("simplified_primary_heating_fuel", "state_abbr"), 
                                          metric_name="energy_cost", 
                                          metric_cutoff_level=0, 
                                          upper_quantile_view=1.0, 
                                          lower_quantile_view=0.0)
```

```{r}
calculate_weighted_metrics(st_drop_geometry(clean_data_fpl_all_sup_shp), 
                                          group_columns=c("state_abbr"), 
                                          metric_name="electricity_spend", 
                                          metric_cutoff_level=0, 
                                          upper_quantile_view=1.0, 
                                          lower_quantile_view=0.0)
```

```{r}
energy_cost_fuel_wm <- calculate_weighted_metrics(st_drop_geometry(clean_data_ami_all_sup_shp), 
                                         group_columns=c("NERC Region"), 
                                         metric_name="energy_cost", 
                                         metric_cutoff_level=0, 
                                         upper_quantile_view=1.0, 
                                         lower_quantile_view=0.0)
energy_cost_fuel_wm
```


```{r}
neb_nerc_wm <- calculate_weighted_metrics(st_drop_geometry(clean_data_ami_all_sup_shp), 
                                         group_columns=c("NERC Region"), 
                                         metric_name="neb", 
                                         metric_cutoff_level=metric_cutoff_level, 
                                         upper_quantile_view=1.0, 
                                         lower_quantile_view=0.0)
neb_nerc_wm
```


```{r}
plot((nerc_regions["NAME"]))#, col = sf.colors(categorical = TRUE, alpha = .5))
```

```{r}
SERC_REGIONS <- c("SERC RELIABILITY CORPORATION (SERC)",
                                   "FLORIDA RELIABILITY COORDINATING COUNCIL (FRCC)")

plot((nerc_regions["NAME"] %>% filter(NAME %in% SERC_REGIONS)))#, col = sf.colors(categorical = TRUE, alpha = .5))
```


```{r}
# intersect - note that sf is intelligent with attribute data!
serc_subset <- st_intersection(clean_data_ami_all_sup_shp, 
              nerc_regions %>% 
                filter(NAME %in% SERC_REGIONS) %>% 
                st_transform(., 4326)
                )

plot(serc_subset$geometry)
```




```{r}
serc_wm <- calculate_weighted_metrics(st_drop_geometry(serc_subset), 
                                         group_columns=c("state_abbr"), 
                                         metric_name="electricity_spend", 
                                         metric_cutoff_level=0, 
                                         upper_quantile_view=1.0, 
                                         lower_quantile_view=0.0)
serc_wm
```


```{r}
serc_subset %>% group_by(
  "state_abbr"
) %>% 
  summarize(
    ave_spend = mean("electricity_spend", na.rm = TRUE),
    total_households = sum("households")
  ) %>% 
  mutate(
    total_revenue = ave_spend + total_households
  ) %>% 
  mutate(
    market_share = total_revenue / sum(total_revenue)
  )
```


```{r}
plot(pi$geometry, axes = TRUE)
plot(pi$geoms, add = TRUE)
plot(pi$geometry, add = TRUE, col = 'red')

# add in areas in m2
attArea <- pi %>% 
  mutate(area = st_area(.) %>% as.numeric())

# for each field, get area per soil type
attArea %>% 
  as_tibble() %>% 
  group_by(field, soil) %>% 
  summarize(area = sum(area))
```


```{r}
st_intersects(clean_data_ami_all_sup_shp, 
              nerc_regions %>% 
                filter(NAME=="SERC RELIABILITY CORPORATION (SERC)") %>% 
                st_transform(., 4326)) %>% 
  st_geometry() %>% 
  plot(col = sf.colors(categorical = TRUE, alpha = .5))
```


```{r}
clean_data_ami_all_sup_shp %>% 
   %>%
  head()
```


```{r}
poster_charts <- make_all_charts(
  clean_data=clean_data_ami_all_sup_shp, #clean_data_ami_all_sup_shp, 
  group_columns=c(NULL),
  metric_name=metric_name, 
  metric_long_name=metric_long_name,
  metric_label=metric_label,
  metric_cutoff_level = metric_cutoff_level,
  metric_cutoff_label= NULL,
  weighted_metrics_data = clean_data_ami_all_sup_shp,
  upper_quantile_view=0.95,
  lower_quantile_view=0.05,
  border_field = "tract_fips",
  include_basemap = "toner-lite",
  keep_coordinates=TRUE,
  infer_missing="max"
)
```

```{r}

```



```{r}
# limit to census tracts in SERC
clean_data_ami_all_sup_shp_serc <- clean_data_ami_all_sup_shp %>% 
  filter(
    `NERC Region`=="SERC"
  )
```

```{r}
clean_data_ami_all_sup_shp_continent <- 
  clean_data_ami_all_sup_shp %>% 
  filter(!(state_abbr %in% c("HI","AK", NA)))
```
