# Auto-generated smoke tests for emburden
# Generated by scripts/generate_test_suites.R (emburdensynth).
# Purpose: assert each flagship export exists + has a callable signature.
# Add hand-written unit tests to other test-*.R files as behaviour is added.

test_that("package emburden can be loaded", {
  expect_no_error(requireNamespace("emburden", quietly = TRUE))
})

test_that("15 flagship exports exist as callable objects", {
  # Each export should resolve to a real object in the package namespace
  expect_true(exists(""%>%"", envir = asNamespace("emburden")),
              info = ""%>%" should be exported from emburden")
  expect_true(exists("calculate_weighted_metrics", envir = asNamespace("emburden")),
              info = "calculate_weighted_metrics should be exported from emburden")
  expect_true(exists("check_data_sources", envir = asNamespace("emburden")),
              info = "check_data_sources should be exported from emburden")
  expect_true(exists("clear_all_cache", envir = asNamespace("emburden")),
              info = "clear_all_cache should be exported from emburden")
  expect_true(exists("clear_dataset_cache", envir = asNamespace("emburden")),
              info = "clear_dataset_cache should be exported from emburden")
  expect_true(exists("colorize", envir = asNamespace("emburden")),
              info = "colorize should be exported from emburden")
  expect_true(exists("compare_energy_burden", envir = asNamespace("emburden")),
              info = "compare_energy_burden should be exported from emburden")
  expect_true(exists("dear_func", envir = asNamespace("emburden")),
              info = "dear_func should be exported from emburden")
  expect_true(exists("energy_burden_func", envir = asNamespace("emburden")),
              info = "energy_burden_func should be exported from emburden")
  expect_true(exists("eroi_func", envir = asNamespace("emburden")),
              info = "eroi_func should be exported from emburden")
  expect_true(exists("get_dataset_info", envir = asNamespace("emburden")),
              info = "get_dataset_info should be exported from emburden")
  expect_true(exists("get_income_brackets", envir = asNamespace("emburden")),
              info = "get_income_brackets should be exported from emburden")
  expect_true(exists("lead_to_poverty", envir = asNamespace("emburden")),
              info = "lead_to_poverty should be exported from emburden")
  expect_true(exists("list_cohort_columns", envir = asNamespace("emburden")),
              info = "list_cohort_columns should be exported from emburden")
  expect_true(exists("list_income_brackets", envir = asNamespace("emburden")),
              info = "list_income_brackets should be exported from emburden")
})

test_that("exports are functions or expected data objects", {
  ns <- asNamespace("emburden")
  obj <- get(""%>%"", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = ""%>%" should be a function or a data object")
  obj <- get("calculate_weighted_metrics", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "calculate_weighted_metrics should be a function or a data object")
  obj <- get("check_data_sources", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "check_data_sources should be a function or a data object")
  obj <- get("clear_all_cache", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "clear_all_cache should be a function or a data object")
  obj <- get("clear_dataset_cache", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "clear_dataset_cache should be a function or a data object")
  obj <- get("colorize", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "colorize should be a function or a data object")
  obj <- get("compare_energy_burden", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "compare_energy_burden should be a function or a data object")
  obj <- get("dear_func", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "dear_func should be a function or a data object")
  obj <- get("energy_burden_func", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "energy_burden_func should be a function or a data object")
  obj <- get("eroi_func", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "eroi_func should be a function or a data object")
  obj <- get("get_dataset_info", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "get_dataset_info should be a function or a data object")
  obj <- get("get_income_brackets", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "get_income_brackets should be a function or a data object")
  obj <- get("lead_to_poverty", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "lead_to_poverty should be a function or a data object")
  obj <- get("list_cohort_columns", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "list_cohort_columns should be a function or a data object")
  obj <- get("list_income_brackets", envir = ns)
  expect_true(is.function(obj) || is.list(obj) || is.character(obj) || is.numeric(obj) || is.data.frame(obj),
              info = "list_income_brackets should be a function or a data object")
})

