#!/usr/bin/env Rscript
# Auto-generate R/zenodo.R from state-manifest.json and zenodo-config-nationwide.txt
#
# This script ensures R/zenodo.R stays in sync with the actual generated files
# by reading the "source of truth" (state-manifest.json) and Zenodo metadata.
#
# Usage: Rscript .dev/update-zenodo-config.R

cat("\n")
cat("==========================================\n")
cat("  Auto-generate R/zenodo.R Configuration\n")
cat("==========================================\n\n")

# Load required packages
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  stop("Package 'jsonlite' required. Install with: install.packages('jsonlite')")
}

# Read state manifest (source of truth for file metadata)
manifest_path <- "zenodo-upload-nationwide/state-manifest.json"
if (!file.exists(manifest_path)) {
  stop("state-manifest.json not found at: ", manifest_path)
}

cat("Reading state-manifest.json...\n")
manifest <- jsonlite::read_json(manifest_path)

# Read Zenodo config (for DOIs and record ID)
zenodo_config_path <- "zenodo-upload-nationwide/zenodo-config-nationwide.txt"
if (!file.exists(zenodo_config_path)) {
  stop("zenodo-config-nationwide.txt not found. Run upload script first.")
}

cat("Reading zenodo-config-nationwide.txt...\n")
zenodo_config <- readLines(zenodo_config_path)

# Extract DOIs and record ID
concept_doi <- sub('CONCEPT_DOI="(.*)"', '\\1', grep("^CONCEPT_DOI=", zenodo_config, value = TRUE))
version_doi <- sub('VERSION_DOI="(.*)"', '\\1', grep("^VERSION_DOI=", zenodo_config, value = TRUE))
record_id <- sub('RECORD_ID="(.*)"', '\\1', grep("^RECORD_ID=", zenodo_config, value = TRUE))
record_url <- sub('RECORD_URL="(.*)"', '\\1', grep("^RECORD_URL=", zenodo_config, value = TRUE))

if (length(concept_doi) == 0 || length(version_doi) == 0 || length(record_id) == 0) {
  stop("Could not extract DOIs/record ID from zenodo-config-nationwide.txt")
}

cat("\nZenodo Record Information:\n")
cat("  Concept DOI: ", concept_doi, "\n")
cat("  Version DOI: ", version_doi, "\n")
cat("  Record ID:   ", record_id, "\n")
cat("  Record URL:  ", record_url, "\n\n")

# Generate the files configuration section
cat("Generating file configuration...\n")

datasets <- c("ami_2022", "fpl_2022", "ami_2018", "fpl_2018")
files_config <- character()

for (dataset in datasets) {
  if (!dataset %in% names(manifest$nationwide)) {
    warning("Dataset '", dataset, "' not found in manifest. Skipping.")
    next
  }

  info <- manifest$nationwide[[dataset]]

  # Format the R list code
  file_config <- sprintf('      %s = list(
        filename = "%s",
        url = "%s/files/%s",
        size_mb = %.2f,
        md5 = "%s"
      )',
    dataset,
    info$filename,
    record_url,
    info$filename,
    info$size_mb,
    info$md5
  )

  files_config <- c(files_config, file_config)
}

# Add census_tracts placeholder
files_config <- c(files_config, sprintf('
      # Census Tract Data (not yet uploaded)
      census_tracts = list(
        filename = "census_tract_data.csv.gz",
        url = NULL,
        size_mb = NULL,
        md5 = NULL
      )'))

files_section <- paste(files_config, collapse = ",\n\n")

# Read current R/zenodo.R file
zenodo_r_path <- "R/zenodo.R"
if (!file.exists(zenodo_r_path)) {
  stop("R/zenodo.R not found at: ", zenodo_r_path)
}

cat("Reading R/zenodo.R...\n")
current_code <- readLines(zenodo_r_path)

# Generate new get_zenodo_config() function
new_function <- sprintf('get_zenodo_config <- function() {
  # Zenodo record for emburden processed datasets
  # Published: %s
  # Scope: US Nationwide (51 states + DC)
  # This record contains pre-processed, analysis-ready datasets
  #
  # AUTO-GENERATED by .dev/update-zenodo-config.R
  # DO NOT EDIT MANUALLY - regenerate from state-manifest.json instead
  list(
    # Main repository DOI (concept DOI - always points to latest version)
    concept_doi = "%s",

    # Version-specific DOI (for reproducibility)
    version_doi = "%s",

    # Direct download URLs for each dataset
    # Format: zenodo_baseurl/records/RECORD_ID/files/FILENAME
    files = list(
      # 2022 Cohort Data (US Nationwide)
%s
    ),

    # Metadata
    description = "Pre-processed DOE LEAD Tool data for emburden R package (US Nationwide)",
    license = "CC-BY-4.0",
    source = "DOE Low-Income Energy Affordability Data (LEAD) Tool"
  )
}',
  format(Sys.Date(), "%Y-%m-%d"),
  concept_doi,
  version_doi,
  files_section
)

# Find the start and end of get_zenodo_config() in current file
start_line <- grep("^get_zenodo_config <- function\\(\\)", current_code)
end_line <- grep("^}$", current_code)

if (length(start_line) == 0) {
  stop("Could not find get_zenodo_config() function in R/zenodo.R")
}

# Find the closing brace that matches this function
# (the first } after the start that's at the same indentation level)
end_line <- end_line[end_line > start_line[1]][1]

if (is.na(end_line)) {
  stop("Could not find end of get_zenodo_config() function")
}

# Build new file content
new_code <- c(
  current_code[1:(start_line - 1)],    # Everything before function
  new_function,                         # New function
  current_code[(end_line + 1):length(current_code)]  # Everything after function
)

# Write updated file
cat("Writing updated R/zenodo.R...\n")
writeLines(new_code, zenodo_r_path)

cat("\n")
cat("==========================================\n")
cat("  SUCCESS: R/zenodo.R updated!\n")
cat("==========================================\n\n")

cat("Summary of changes:\n")
cat("  - Updated Concept DOI: ", concept_doi, "\n")
cat("  - Updated Version DOI: ", version_doi, "\n")
cat("  - Updated file configurations for:\n")
for (dataset in datasets) {
  if (dataset %in% names(manifest$nationwide)) {
    info <- manifest$nationwide[[dataset]]
    cat(sprintf("    * %s: MD5=%s, Size=%.2f MB\n",
                dataset, info$md5, info$size_mb))
  }
}

cat("\nNext steps:\n")
cat("  1. Review changes: git diff R/zenodo.R\n")
cat("  2. Validate: Rscript .dev/validate-zenodo-checksums.R\n")
cat("  3. Commit if correct: git add R/zenodo.R && git commit\n\n")
