#!/usr/bin/env Rscript
# Auto-update R/zenodo.R with new Zenodo DOIs and URLs
#
# This script reads the zenodo-config-nationwide.txt file generated by
# upload-to-zenodo-nationwide.sh and updates R/zenodo.R automatically.
#
# Usage: Rscript .dev/update-zenodo-config.R

library(jsonlite)

# Configuration
config_file <- "zenodo-upload-nationwide/zenodo-config-nationwide.txt"
manifest_file <- "zenodo-upload-nationwide/state-manifest.json"
zenodo_r_file <- "R/zenodo.R"

cat("\n")
cat("================================================================================\n")
cat("  Auto-Update Zenodo Configuration\n")
cat("================================================================================\n\n")

# Step 1: Read Zenodo config file
if (!file.exists(config_file)) {
  stop("Config file not found: ", config_file, "\n",
       "Run .dev/upload-to-zenodo-nationwide.sh first!")
}

cat("Reading configuration from:", config_file, "\n")

# Parse config file (bash format)
config_lines <- readLines(config_file)
config_data <- list()

for (line in config_lines) {
  # Skip comments and empty lines
  if (grepl("^#", line) || grepl("^\\s*$", line)) next

  # Parse KEY="value" format
  if (grepl('=', line)) {
    parts <- strsplit(line, '=')[[1]]
    key <- trimws(parts[1])
    value <- gsub('^"|"$', '', trimws(parts[2]))
    config_data[[key]] <- value
  }
}

concept_doi <- config_data$CONCEPT_DOI
version_doi <- config_data$VERSION_DOI
record_id <- config_data$RECORD_ID

cat("  Concept DOI:", concept_doi, "\n")
cat("  Version DOI:", version_doi, "\n")
cat("  Record ID:", record_id, "\n\n")

# Step 2: Read manifest for file sizes and MD5s
cat("Reading manifest from:", manifest_file, "\n")
manifest <- fromJSON(manifest_file, simplifyVector = FALSE)

# Extract file info
files_info <- list()
for (dataset_key in names(manifest$nationwide)) {
  file_data <- manifest$nationwide[[dataset_key]]
  files_info[[dataset_key]] <- list(
    filename = file_data$filename,
    size_mb = file_data$size_mb,
    md5 = file_data$md5
  )
  cat("  -", dataset_key, ":", file_data$filename, "\n")
}
cat("\n")

# Step 3: Construct URLs for each file
cat("Constructing file URLs...\n")

file_configs <- list()
base_url <- paste0("https://zenodo.org/records/", record_id, "/files/")

for (dataset_key in c("ami_2022", "fpl_2022", "ami_2018", "fpl_2018")) {
  if (dataset_key %in% names(files_info)) {
    info <- files_info[[dataset_key]]
    url <- paste0(base_url, info$filename)

    file_configs[[dataset_key]] <- list(
      filename = info$filename,
      url = url,
      size_mb = info$size_mb,
      md5 = info$md5
    )

    cat("  ", dataset_key, ":\n")
    cat("    URL:", url, "\n")
    cat("    Size:", info$size_mb, "MB\n")
    cat("    MD5:", info$md5, "\n")
  }
}
cat("\n")

# Step 4: Generate new get_zenodo_config() function
cat("Generating updated get_zenodo_config() function...\n")

new_function <- sprintf('get_zenodo_config <- function() {
  # Zenodo record for emburden processed datasets
  # Published: %s
  # Scope: US Nationwide (51 states + DC)
  # This record contains pre-processed, analysis-ready datasets
  list(
    # Main repository DOI (concept DOI - always points to latest version)
    concept_doi = "%s",

    # Version-specific DOI (for reproducibility)
    version_doi = "%s",

    # Direct download URLs for each dataset
    # Format: zenodo_baseurl/records/RECORD_ID/files/FILENAME
    files = list(
      # 2022 Cohort Data (US Nationwide)
      ami_2022 = list(
        filename = "%s",
        url = "%s",
        size_mb = %.2f,
        md5 = "%s"
      ),
      fpl_2022 = list(
        filename = "%s",
        url = "%s",
        size_mb = %.2f,
        md5 = "%s"
      ),

      # 2018 Cohort Data (US Nationwide)
      ami_2018 = list(
        filename = "%s",
        url = "%s",
        size_mb = %.2f,
        md5 = "%s"
      ),
      fpl_2018 = list(
        filename = "%s",
        url = "%s",
        size_mb = %.2f,
        md5 = "%s"
      ),

      # Census Tract Data (not yet uploaded)
      census_tracts = list(
        filename = "census_tract_data.csv.gz",
        url = NULL,
        size_mb = NULL,
        md5 = NULL
      )
    ),

    # Metadata
    description = "Pre-processed DOE LEAD Tool data for emburden R package (US Nationwide)",
    license = "CC-BY-4.0",
    source = "DOE Low-Income Energy Affordability Data (LEAD) Tool"
  )
}',
  format(Sys.Date(), "%Y-%m-%d"),
  concept_doi,
  version_doi,
  # AMI 2022
  file_configs$ami_2022$filename,
  file_configs$ami_2022$url,
  file_configs$ami_2022$size_mb,
  file_configs$ami_2022$md5,
  # FPL 2022
  file_configs$fpl_2022$filename,
  file_configs$fpl_2022$url,
  file_configs$fpl_2022$size_mb,
  file_configs$fpl_2022$md5,
  # AMI 2018
  file_configs$ami_2018$filename,
  file_configs$ami_2018$url,
  file_configs$ami_2018$size_mb,
  file_configs$ami_2018$md5,
  # FPL 2018
  file_configs$fpl_2018$filename,
  file_configs$fpl_2018$url,
  file_configs$fpl_2018$size_mb,
  file_configs$fpl_2018$md5
)

# Step 5: Read current R/zenodo.R
cat("Reading current R/zenodo.R...\n")
zenodo_r_lines <- readLines(zenodo_r_file)

# Step 6: Replace get_zenodo_config() function
cat("Updating get_zenodo_config() function...\n")

# Find function start and end
start_idx <- which(grepl("^get_zenodo_config <- function\\(\\)", zenodo_r_lines))
if (length(start_idx) == 0) {
  stop("Could not find get_zenodo_config() function in R/zenodo.R")
}

# Find matching closing brace
brace_count <- 0
end_idx <- start_idx

for (i in start_idx:length(zenodo_r_lines)) {
  line <- zenodo_r_lines[i]

  # Count braces
  open_braces <- length(gregexpr("\\{", line)[[1]])
  close_braces <- length(gregexpr("\\}", line)[[1]])

  if (open_braces > 0) {
    brace_count <- brace_count + sum(nchar(gsub("[^{]", "", line)))
  }
  if (close_braces > 0) {
    brace_count <- brace_count - sum(nchar(gsub("[^}]", "", line)))
  }

  if (brace_count == 0 && i > start_idx) {
    end_idx <- i
    break
  }
}

cat("  Found function at lines", start_idx, "-", end_idx, "\n")

# Construct new file content
new_lines <- c(
  zenodo_r_lines[1:(start_idx - 1)],
  strsplit(new_function, "\n")[[1]],
  zenodo_r_lines[(end_idx + 1):length(zenodo_r_lines)]
)

# Step 7: Write updated file
cat("Writing updated R/zenodo.R...\n")
writeLines(new_lines, zenodo_r_file)

cat("\n")
cat("✓ Successfully updated R/zenodo.R!\n")
cat("\n")
cat("Next steps:\n")
cat("  1. Review changes: git diff R/zenodo.R\n")
cat("  2. Test downloads: devtools::test_file('tests/testthat/test-zenodo-download.R')\n")
cat("  3. Commit and push changes\n")
cat("\n")
